version: '3.7'

services:
  server:
    build:
      context: .
      target: builder
    ports:
      - 8888:8888
    environment:
      PORT: 8888
    volumes:
      - .:/build
    command:  bash -c "air server"
    working_dir: /build
