version: '3.7'

services:
  server:
    build:
      context: .
      target: builder
    ports:
      - 8888:8888
    environment:
      PORT: 8888
    volumes:
      - .:/build
    working_dir: /build
    command: bash -c "air server"

  front:
    image: node:19-buster
    ports:
      - 7777:7777
    environment:
      PORT: 7777
    volumes:
      - ./front:/home
    working_dir: /home
    command: npm run start
