name: Heroku

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: deploy heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          heroku container:login
          docker pull ghcr.io/kijimad/golife_heroku:latest
          docker tag ghcr.io/kijimad/golife_heroku:latest registry.heroku.com/kd-golife/web
          docker push registry.heroku.com/kd-golife/web
          heroku container:release web -a=kd-golife
