name: 🚀Publish to GHP

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd ./front && \
          npm install && \
          npm run production

      - name: Check
        run: ls -al ./front/build

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: front/build
